---
- hosts: mi-pi
  vars:
    ntp_server: 10.15.1.250
  become: yes
  tasks:
  - name: write the timesyncd config file
    template:
      src: timesyncd.conf.j2
      dest: /etc/systemd/timesyncd.conf
    notify:
    - set-ntp-true
    - restart timesyncd
  - name: ensure systemd-timesyncd is running
    service:
      name: systemd-timesyncd
      state: started
  - name: ensure systemd-timedated is running
    service:
      name: systemd-timedated
      state: started
  handlers:
    - name: restart timesyncd
      service:
        name: systemd-timesyncd
        state: restarted
    - name: set-ntp-true
      shell: /usr/bin/timedatectl set-ntp true


